[build]
  base    = "docs/"
  publish = "build/"
  command = "yarn && yarn build"
  ignore  = "git diff --quiet HEAD^ HEAD ."

[build.environment]
NODE_VERSION = "16.14.0"
NODE_OPTIONS = "--max_old_space_size=4096"
NETLIFY_USE_YARN = "true"
YARN_VERSION = "1.22.10"
