name: Lint, Test and Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - run: yarn install --frozen-lockfile --check-files
      - name: Prettier
        run: yarn prettier:ci
      - name: Lint
        run: yarn eslint:ci
      - name: Type Check
        run: yarn test:types
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
