name: Lint, Test and Build

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  lint:
    name: Lint, Test and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      # - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install --frozen-lockfile --check-files
      - name: Prettier
        run: yarn prettier:ci
      - name: Lint
        run: yarn eslint:ci
      - name: Type Check
        run: yarn test:types
      - name: Test
        run: yarn test
      - name: Build
        run: yarn build
